Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false  

Lint/UnusedBlockArgument:
  Enabled: false

Lint/DuplicateHashKey:
  Enabled: false  
  
Metrics/AbcSize:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GlobalVars:
  Enabled: No
  
Style/HashSyntax:
  Enabled: false

Style/RedundantReturn:
  Enabled: false  

convention:Layout/LineLength:
  Enabled: false

convention:Style/TrailingCommaInArguments:
  Enabled: false

convention:Naming/AccessorMethodName: 
  Enabled: false

convention:Naming/PredicateName:
  Enabled: false

convention:Style/GuardClause:
  Enabled: false