source "https://rubygems.org"

gem "allure-rspec"
gem "appium_capybara"
gem "appium_lib"
gem "browserstack-local"
gem "capybara"
gem "httparty"
gem "rake"
gem "rspec"
gem "selenium-webdriver"
gem "site_prism"
gem "yaml"
