user_credentials:
  username: "admin"
  password: "admin"

views:
  first_view: "Hello World, I'm View one"
  second_view: "Hello World, I'm View two"
  third_view: "Hello World, I'm View three"

technologies:
  one: ".NET"
  two: "MySQL"
  three: "Appium"
  four: "Jest"
  five: "Karma"